name       : leafpad
version    : 0.8.19
release    : 4
source     :
    - http://download.savannah.gnu.org/releases/leafpad/leafpad-0.8.19.tar.gz : 07d3f712f4dbd0a33251fd1dee14e21afdc9f92090fc768c11ab0ac556adbe97
homepage   : http://tarot.freeshell.org/leafpad/
license    : GPL-2.0-or-later
component  : editor
summary    : GTK+ based simple text editor
description: |
    Leafpad is a simple GTK+ text editor that emphasizes simplicity. As development focuses on keeping weight down to a minimum, only the most essential features are implemented in the editor. Leafpad is simple to use, is easily compiled, requires few libraries, and starts up quickly.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(gtk+-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
