name       : leafpad
version    : 0.8.18.1
release    : 2
source     :
    - http://download.savannah.gnu.org/releases/leafpad/leafpad-0.8.18.1.tar.gz : 959d22ae07f22803bc66ff40d373a854532a6e4732680bf8a96a3fbcb9f80a2c
license    : GPL
component  : editor
summary    : GTK+ based simple text editor
description: |
    GTK+ based simple text editor
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(gtk+-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
