name       : leafpad
version    : 0.8.17
release    : 1
source     :
    - http://savannah.nongnu.org/download/leafpad/leafpad-0.8.17.tar.gz : 8df8de7aaea26148225b6120631b4fe6b89d36d2b52962e7c9cc0ce07bfdbd4c
license    : GPL
summary    : GTK+ based simple text editor
description: |
    GTK+ based simple text editor
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(atk)
    - pkgconfig(cairo)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
